### ISSUE TITLE
RN0.21报错

### ISSUE THREAD

**Issue by zhenlovezhen2012** [hufeng/react-native-baidu-map#10]
``` java
java.lang.AbstractMethodError: abstract method not implemented
                                                       at com.bee.baidumapview.BaiduMapShadowNode.measure(BaiduMapShadowNode.java)
                                                       at com.facebook.csslayout.CSSNode.measure(CSSNode.java:137)
                                                       at com.facebook.csslayout.LayoutEngine.layoutNodeImpl(LayoutEngine.java:294)
                                                       at com.facebook.csslayout.LayoutEngine.layoutNode(LayoutEngine.java:210)
                                                       at com.facebook.csslayout.LayoutEngine.layoutNodeImpl(LayoutEngine.java:633)
                                                       at com.facebook.csslayout.LayoutEngine.layoutNode(LayoutEngine.java:210)
                                                       at com.facebook.csslayout.LayoutEngine.layoutNodeImpl(LayoutEngine.java:633)
                                                       at com.facebook.csslayout.LayoutEngine.layoutNode(LayoutEngine.java:210)
                                                       at com.facebook.csslayout.LayoutEngine.layoutNodeImpl(LayoutEngine.java:492)
                                                       at com.facebook.csslayout.LayoutEngine.layoutNode(LayoutEngine.java:210)
                                                       at com.facebook.csslayout.LayoutEngine.layoutNodeImpl(LayoutEngine.java:633)
                                                       at com.facebook.csslayout.LayoutEngine.layoutNode(LayoutEngine.java:210)
                                                       at com.facebook.csslayout.LayoutEngine.layoutNodeImpl(LayoutEngine.java:633)
                                                       at com.facebook.csslayout.LayoutEngine.layoutNode(LayoutEngine.java:210)
                                                       at com.facebook.csslayout.LayoutEngine.layoutNodeImpl(LayoutEngine.java:492)
                                                       at com.facebook.csslayout.LayoutEngine.layoutNode(LayoutEngine.java:210)
                                                       at com.facebook.csslayout.LayoutEngine.layoutNodeImpl(LayoutEngine.java:492)
                                                       at com.facebook.csslayout.LayoutEngine.layoutNode(LayoutEngine.java:210)
                                                       at com.facebook.csslayout.CSSNode.calculateLayout(CSSNode.java:146)
                                                       at com.facebook.react.uimanager.UIImplementation.calculateRootLayout(UIImplementation.java:674)
                                                       at com.facebook.react.uimanager.UIImplementation.dispatchViewUpdates(UIImplementation.java:445)
                                                       at com.facebook.react.uimanager.UIManagerModule.onBatchComplete(UIManagerModule.java:423)
                                                       at com.facebook.react.bridge.NativeModuleRegistry.onBatchComplete(NativeModuleRegistry.java:119)
                                                       at com.facebook.react.bridge.CatalystInstanceImpl$NativeModulesReactCallback.onBatchComplete(CatalystInstanceImpl.java:442)
                                                       at com.facebook.react.bridge.queue.NativeRunnableDeprecated.run(Native Method)
                                                       at android.os.Handler.handleCallback(Handler.java:733)
                                                       at android.os.Handler.dispatchMessage(Handler.java:95)
                                                       at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
                                                       at android.os.Looper.loop(Looper.java:136)
                                                       at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:184)
                                                       at java.lang.Thread.run(Thread.java:841)
```

**Comment by hufeng** [comment]
估计rn的api，又发生了变动。我来看下

**Comment by aq2004723** [comment]
RN 0.23 了 估计 api变化了很多吧。。。 在0.23上报错
